# Generated by Django 5.0.6 on 2024-06-25 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='newsletter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='mail_app.newsletter', verbose_name='Рассылка'),
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt', to='mail_app.newsletter', verbose_name='Рассылка'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter', to='mail_app.message'),
        ),
    ]
