# Generated by Django 5.0.6 on 2024-06-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0002_alter_client_newsletter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('Создана', 'CREATE'), ('Запущена', 'START'), ('Остановлена', 'STOP')], default='CREATE', max_length=255, verbose_name='Статус'),
        ),
    ]
