# Generated by Django 5.0.6 on 2024-06-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0004_alter_newsletter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('Активный', 'Активный'), ('Неактивный', 'Неактивный'), ('Новый', 'Новый'), ('Потенциальный', 'Потенциальный'), ('Заблокированный', 'Заблокированный'), ('Неизвестный', 'Неизвестный')], default='Неизвестный', max_length=255),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Остановлена', 'Остановлена')], default='Создана', max_length=255, verbose_name='Статус'),
        ),
    ]
