# Generated by Django 5.0.6 on 2024-06-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0006_client_slug_newsletter_slug_alter_newsletter_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='slug',
            field=models.SlugField(default='default', max_length=255, unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
