# Generated by Django 5.0.6 on 2024-06-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0007_alter_client_slug_alter_newsletter_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название рассылки'),
        ),
    ]
