# Generated by Django 5.0.6 on 2024-07-04 14:12

from django.db import migrations, models
from django.utils import timezone

now = timezone.now()


class Migration(migrations.Migration):
    dependencies = [
        ('mail_app',
         '0009_newsletter_last_sent_at_alter_newsletter_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='first_sent_at',
            field=models.DateTimeField(
                default=now,
                verbose_name='Дата первого отправления'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='last_sent_at',
            field=models.DateTimeField(
                default=now,
                verbose_name='Дата крайнего отправления'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='periodicity',
            field=models.CharField(
                choices=[('День', 'День'), ('Неделя', 'Неделя'),
                         ('Месяц', 'Месяц'), ('Год', 'Год')], default='Год',
                max_length=255, verbose_name='Периодичность'),
        ),
    ]
