# Generated by Django 5.0.6 on 2024-07-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0012_alter_newsletter_first_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='count_delivered',
            field=models.IntegerField(default=0, verbose_name='Количество доставленных'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='count_sent',
            field=models.IntegerField(default=0, verbose_name='Количество отправленных'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='count_transition',
            field=models.IntegerField(default=0, verbose_name='Количество переходов'),
        ),
    ]
