# Generated by Django 4.2 on 2024-08-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0016_remove_client_newsletter_client_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='newsletter',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='clients',
            field=models.ManyToManyField(related_name='newsletter', to='mail_app.client', verbose_name='Клиенты'),
        ),
    ]
