# Generated by Django 4.2 on 2024-08-02 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Статья блога', 'verbose_name_plural': 'Статьи блога'},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='information',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='count_view',
            new_name='count_views',
        ),
    ]
